export const constants = {
  LOADING: "LOADING",
  GET_RECIPES: "GET_RECIPES",
  GET_RECIPE_BY_ID: "GET_RECIPE_BY_ID",
  GET_RECIPE_BY_NAME: "GET_RECIPE_BY_NAME",
  FILTER_RECIPES_BY_ORIGIN: "FILTER_RECIPES_BY_ORIGIN",
  FILTER_RECIPES_BY_DIET: "FILTER_RECIPES_BY_DIET",
  SORT_RECIPES_BY_NAME: "SORT_RECIPES_BY_NAME",
  SORT_RECIPES_BY_SCORE: "SORT_RECIPES_BY_SCORE",
  GET_DIETS: "GET_DIETS",
};